services:
  gateway:
    image: nginx:alpine
    ports:
      - "${TEAM_PORT}:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - CORE_BASE_URL=http://team7:8000
    depends_on:
      - team7
    networks:
      - app404
  #   depends_on:
  #     - frontend
  #     - backend
  
  # frontend:
  #   image: traefik/whoami
  #   command: ["-port=5173"]
  #   networks:
  #     - app404

  # backend:
  #   image: traefik/whoami
  #   command: ["-port=3000"]
  #   networks:
  #     - app404

  team7:
    build: .
    container_name: team7_service
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DJANGO_SETTINGS_MODULE=core.settings
    expose:
      - "8000"
    networks:
      - app404

networks:
  app404:
    external: true
    name: app404_net

